import json
import config
from pony.orm import *

'''
The entity module contains all the entities of your application.
We will be using PonyORM; please, refer to http:ponyorm.com for more info.
'''

# instance of the class Database to create and map tables
db = Database()

'''
    Student entity class
    ====================
    Each student has a unique student_id (automatically generated by the DB),
    a firstname, a lastname, and a list of courses and exams.
'''
class Student(db.Entity):
    student_id = PrimaryKey(int, auto=True)
    firstname = Required(str)
    lastname  = Required(str)
    courses = Set('Course')
    exams = Set('Exam')

'''
    Course entity class
    ====================
    Each Course has a unique course_id (automatically generated by the DB),
    a name, and a list of students and exams.
'''
class Course(db.Entity):
    course_id  = PrimaryKey(int, auto=True)
    name = Required(str)
    students = Set('Student')
    exams = Set('Exam')


'''
    Exam entity class
    ====================
    Each exam point to a student and a course, and it has an optional
    text attribut for registering a mark.
'''
class Exam(db.Entity):
    student = Required('Student')
    course = Required('Course')
    mark   = Optional(int)

#######################################################
### The following 2 instructions bind the db to the
### SQLite file and generate the tables if needed.
#######################################################
# binding the entities to an sqlite database
db.bind('sqlite', config.DB_FILE_NAME, create_db=True)

# create the tables
db.generate_mapping(create_tables=True)
